import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "./component/Nav";
import Link from "next/link";

// pages
import Start from "./Start";
import Intro from "./Intro";
import Portfolio from "./Portfolio";
import Contact from "./Contact";
import Sushi from "./Sushi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Nav />
        <div className="sushi-wrapper">
          <h5>Hi! I am</h5>
          <h1>SUSHANT CHHETRY</h1>
          <Sushi />
          <div className="btn-wrapper">
            <button className="btn">Resume</button>
            <Link href={"#contact"}>
              <button className="btn">Connect</button>
            </Link>
          </div>
        </div>
        <section id="intro">
          <div class="bento-box">
            <h3>Who is Sushant?</h3>

            <div class="compartment big">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
                finibus hendrerit diam, id pellentesque lacus placerat et.
                Aliquam ut ultrices arcu. Vestibulum bibendum sed ligula non
                tristique. Nam aliquam pellentesque arcu et vestibulum. Donec
                quam libero, eleifend sed vehicula sed, rutrum vel massa. In
                vestibulum est vitae arcu convallis, non varius nunc posuere.
              </p>
            </div>
            <div class="compartment">
              <ul>
                <li>Logo</li>
                <li>Logo</li>
                <li>Logo</li>
              </ul>
            </div>
            <div class="compartment">
              <ul>
                <li>Logo</li>
                <li>Logo</li>
                <li>Logo</li>
              </ul>
            </div>
          </div>
        </section>
        <section id="portfolio"></section>
        <section id="contact"></section>
      </main>
    </>
  );
}
