import Head from "next/head";
import Nav from "../component/Nav";
import Link from "next/link";

// parallax
import { ParallaxProvider, Parallax } from "react-scroll-parallax";

// pages
import Contact from "./Contact";
import Sushi from "./Sushi";
import { useState, useEffect } from "react";
import NewIntro from "./NewIntro";
import Portfolio from "./portfolio";

//components
import Loading from "../component/Loading";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [hovered, setHovered] = useState(false);

  const handleMouseEnter = () => {
    setHovered(true);
  };

  const handleMouseLeave = () => {
    setHovered(false);
  };

  useEffect(() => {
    setTimeout(() => setLoading(false), 3000);
  }, []);

  return (
    <>
      <Head>
        <title>Sushant Chhetry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sushi.png" />
      </Head>
      {loading === false ? (
        <main>
          <Nav />
          <ParallaxProvider>
            <Parallax translateY={[-15, 15]}>
              <div className="sushi-wrapper">
                <h5>Hi! I am</h5>
                <div className="header-wrapper">
                  <h1
                    className={hovered ? "header-hover" : "header"}
                    onMouseEnter={handleMouseEnter}
                    onMouseLeave={handleMouseLeave}
                  >
                    {hovered ? "SUSHI" : "SUSHANT"}
                  </h1>
                </div>

                <Sushi />
                <div className="btn-wrapper">
                  <Link href={"/Resume"} target="_blank">
                    <button className="btn">Resume</button>
                  </Link>
                  <Link href={"#contact"}>
                    <button className="btn">Connect</button>
                  </Link>
                </div>
              </div>
            </Parallax>
          </ParallaxProvider>
          <section id="intro">
            <NewIntro />
          </section>
          <section id="portfolio">
            <Portfolio />
          </section>
          <section id="contact">
            <Contact />
          </section>
        </main>
      ) : (
        <Loading />
      )}
    </>
  );
}
