import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "./component/Nav";

// pages
import Start from "./Start";
import Intro from "./Intro";
import Portfolio from "./Portfolio";
import Contact from "./Contact";
import Sushi from "./Sushi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Nav />
        <div className="sushi-wrapper">
          <h5>Hi! I am</h5>
          <h1>SUSHANT CHHETRY</h1>
          <Sushi />
          <div className="btn-wrapper">
            <button className="btn">Resume</button>
            <button className="btn">Connect</button>
          </div>
        </div>
      </main>
    </>
  );
}
